vich_uploader:
    db_driver: orm

    mappings:
            poster_file:
                uri_prefix: /images/posters
                upload_destination: '%upload_directory%'
                namer:
                    service: Vich\UploaderBundle\Naming\SmartUniqueNamer
